from selenium import webdriver
import random
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.action_chains import ActionChains
import time
import names
import string

nam = names.get_first_name()
rand = random.randint(9000000000,9999999999)
lower_upper_alphabet = string.ascii_letters
clg = random.choice(lower_upper_alphabet)
chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument("--incognito")
driver = webdriver.Chrome(chrome_options=chrome_options,executable_path='C:/Replace/with/your/path/webdriver/chromedriver')
#driver.maximize_window()
actions = ActionChains(driver)
for i in range(20):
	driver.get('http://bit.ly/3t8xMEZ')
	elem = driver.find_element_by_xpath('//*[@id="content"]/landing-event-details/div[2]/div[1]/div/div[1]/div')
	time.sleep(3) 
	elem.click()
	driver.execute_script("window.open()")
	driver.switch_to.window(driver.window_handles[1])
	driver.get('https://mail.tm/en/')
	time.sleep(8) 
	elem = driver.find_element_by_xpath('//*[@id="address"]').click()
	driver.switch_to.window(driver.window_handles[0])
	elem = driver.find_element_by_xpath('//*[@id="phoneEmail"]')
	actions.move_to_element(elem)
	actions.click(elem)
	elem.send_keys(Keys.CONTROL, 'v')
	time.sleep(7) 
	elem = driver.find_element_by_xpath('//*[@id="landing-content"]/auth-auth-page/div/div/div/auth-login-signup/div/auth-initial-login-form/div/div[3]/section/div/form/div[2]/div/button').click()
	time.sleep(13)
	elem = driver.find_element_by_xpath('//*[@id="mat-input-2"]')
	actions.move_to_element(elem)
	actions.click(elem)
	elem.send_keys(str(nam))
	time.sleep(5)
	driver.switch_to.window(driver.window_handles[1])
	time.sleep(10)
	elem = driver.find_element_by_xpath('//*[@id="__layout"]/div/div[2]/main/div/div[2]/ul/li/a/div').click()
	time.sleep(27)
	driver.switch_to.frame(driver.find_element_by_xpath('//*[@id="iFrameResizer0"]'))
	otp = driver.find_element_by_xpath('/html/body/center/div/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr/td/table[4]/tbody/tr/td/div/div[1]/span/strong').text
	driver.switch_to.window(driver.window_handles[0])
	elem = driver.find_element_by_xpath('//*[@id="mat-input-1"]')
	actions.move_to_element(elem)
	actions.click(elem)
	elem.send_keys(otp)
	elem.send_keys(Keys.RETURN)
	time.sleep(8)
	elem = driver.find_element_by_xpath('//*[@id="phone"]')
	actions.move_to_element(elem)
	actions.click(elem)
	elem.send_keys(rand)
	elem = driver.find_element_by_xpath('//*[@id="mat-input-10"]')
	actions.move_to_element(elem)
	actions.click(elem)
	elem.send_keys(clg)
	time.sleep(5)
	elem = driver.find_element_by_xpath('//*[@id="mat-option-2"]/span').click()
	time.sleep(5)
	elem = driver.find_element_by_xpath('//*[@id="payment-button-wrapper"]/button').click()
	actions.perform()
	driver.quit()
